{
 "title": "Devices",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "sensor_id",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.measurementTagValues(\n    bucket: \"data-bucket\",\n    tag: \"sensor_id\",\n    measurement: \"mqtt_consumer\",\n)\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Counter",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"data-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\n  |> filter(fn: (r) => r.sensor_id == \"${sensor_id}\")\n  |> filter(fn: (r) => r._field == \"board_counter\")"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"data-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\n  |> filter(fn: (r) => r.sensor_id == \"${sensor_id}\")\n  |> filter(fn: (r) => r._field == \"bme280_temp\")"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"data-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\n  |> filter(fn: (r) => r.sensor_id == \"${sensor_id}\")\n  |> filter(fn: (r) => r._field == \"bme280_hum\")"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"data-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\n  |> filter(fn: (r) => r.sensor_id == \"${sensor_id}\")\n  |> filter(fn: (r) => r._field == \"bme280_pres\")"
    }
   ]
  },
  { "title": "Particles", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Particles opcn3 sps30",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "query": "\nfrom(bucket: \"data-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\n  |> filter(fn: (r) => r.sensor_id == \"${sensor_id}\")\n  |> filter(fn: (r) => r._field == \"sps30_pm1\" or r._field == \"sps30_pm2\" or r._field == \"sps30_pm10\" or r._field == \"sps30_pm4\" or r._field == \"opcn3_PM1\" or r._field == \"opcn3_PM25\" or r._field == \"opcn3_PM10\")"
    }
   ]
  },
  {
   "title": "Sensor map",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "type": "geomap",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "query": "\nfrom(bucket: \"data-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\n  |> filter(fn: (r) => r.sensor_id == \"${sensor_id}\")\n  |> filter(fn: (r) => r._field == \"AD_socket_1_1\" or r._field == \"AD_socket_1_2\" or r._field == \"AD_socket_2_1\" or r._field == \"AD_socket_2_2\")"
      }
     ]
    }
   ]
  },
  {
   "title": "AD sockets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gas socket 1 & 2 ppm",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "query": "\nfrom(bucket: \"data-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\n  |> filter(fn: (r) => r.sensor_id == \"${sensor_id}\")\n  |> filter(fn: (r) => r._field == \"AD_socket_1_1\" or r._field == \"AD_socket_1_2\" or r._field == \"AD_socket_2_1\" or r._field == \"AD_socket_2_2\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Temperature, Humidity, Pressure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "query": "from(bucket: \"data-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\n  |> filter(fn: (r) => r.sensor_id == \"${sensor_id}\")\n  |> filter(fn: (r) => r._field == \"bme280_temp\")"
      }
     ]
    },
    {
     "title": "Humidity",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "humidity" } },
     "targets": [
      {
       "query": "from(bucket: \"data-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\n  |> filter(fn: (r) => r.sensor_id == \"${sensor_id}\")\n  |> filter(fn: (r) => r._field == \"bme280_hum\")"
      }
     ]
    },
    {
     "title": "Pressure",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
     "targets": [
      {
       "query": "from(bucket: \"data-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\n  |> filter(fn: (r) => r.sensor_id == \"${sensor_id}\")\n  |> filter(fn: (r) => r._field == \"bme280_pres\")"
      }
     ]
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "RSSI",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\nfrom(bucket: \"data-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\n  |> filter(fn: (r) => r.sensor_id == \"${sensor_id}\")\n  |> filter(fn: (r) => r._field == \"rssi\")"
    }
   ]
  },
  {
   "title": "SNR",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\nfrom(bucket: \"data-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\n  |> filter(fn: (r) => r.sensor_id == \"${sensor_id}\")\n  |> filter(fn: (r) => r._field == \"snr\")"
    }
   ]
  },
  {
   "title": "f_port",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\nfrom(bucket: \"data-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\n  |> filter(fn: (r) => r.sensor_id == \"${sensor_id}\")\n  |> filter(fn: (r) => r._field == \"f_port\")"
    }
   ]
  },
  {
   "title": "f_cnt",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\nfrom(bucket: \"data-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\n  |> filter(fn: (r) => r.sensor_id == \"${sensor_id}\")\n  |> filter(fn: (r) => r._field == \"f_cnt\")"
    }
   ]
  },
  {
   "title": "Spreading factor",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\nfrom(bucket: \"data-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\n  |> filter(fn: (r) => r.sensor_id == \"${sensor_id}\")\n  |> filter(fn: (r) => r._field == \"spreading_factor\")"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\nfrom(bucket: \"data-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\n  |> filter(fn: (r) => r.sensor_id == \"${sensor_id}\")\n  |> filter(fn: (r) => r._field == \"bandwidth\")"
    }
   ]
  },
  {
   "title": "dev_eui",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "query": "\nfrom(bucket: \"data-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\n  |> filter(fn: (r) => r.sensor_id == \"${sensor_id}\")\n  |> filter(fn: (r) => r._field == \"dev_eui\")"
    }
   ]
  },
  {
   "title": "dev_eui",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "query": "\nfrom(bucket: \"data-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\n  |> filter(fn: (r) => r.sensor_id == \"${sensor_id}\")\n  |> filter(fn: (r) => r._field == \"gateway_id\")"
    }
   ]
  },
  {
   "title": "Others",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "System board voltages",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "query": "\nfrom(bucket: \"data-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\n  |> filter(fn: (r) => r.sensor_id == \"${sensor_id}\")\n  |> filter(fn: (r) => r._field == \"board_batt_voltage\" or r._field == \"board_solar_voltage\" or r._field == \"board_rail_voltage\")"
      }
     ]
    }
   ]
  }
 ]
}